### PR TITLE
Use consistent formatting conventions

### PR DESCRIPTION
**Pull request by KurtJacobson**
Somewhere along the way somebody has used tabs when modifying the `.tmpl` files, instead of the prevailing 2 spaces per indent style. This makes it difficult to maintain the files, and does not give a good impression to someone who happens to view the source in their browser. This PR attempts to restore consistent formatting, but does not make any material changes to the `.tmpl` files.

If you are inclined to accept this PR, it would probably make sense to squash all the commits before merging.

### CODE REVIEW

**Review by weatherstorm — APPROVED** [review]

**Review by weatherstorm — APPROVED** [review]

**Comment by KurtJacobson** [comment]
Oh boy, we got some heavy duty conflicts there, lol. I was wondering if that was going to happen. I will resolve them so you can merge. It should not be too hard since the changes you made were small.

**Comment by weatherstorm** [comment]
Thank you. I was going to just copy your formatting changes piece by piece but if you can do it with the latest code that would great.

**Comment by KurtJacobson** [comment]
Absolutely! I am just re-basing your changes on-top of my formatting changes to maintain the history, but gosh, all those pesky little `<br>` to `&sdot;` changes :D It makes it easy though since you made a separate commit for each file, thanks!

**Comment by weatherstorm** [comment]
Thanks for all your help on this and other bugs in the template. I really appreciate it!

**Comment by KurtJacobson** [comment]
Of course. I think this is one of the best weewx skins out there.

**Pull request merged**
